title: "eva4eva"
author: "ihbaop"
description: "helloooo"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {url: "https://ihbaop.github.io/", title: "home", sidebaricon: home}
  - {file: "pics.md", title: "pics",  sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: wind, icon: wind-turbine, url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSX1_5PNkAI02jCsBaV7dcoUwjkZr7li8mqvA&s"}
  - {title: insta, icon: instagram, url: "https://www.instagram.com/evaszwajka/"}
  - {title: mail, icon: envelope, url: "mailto:ihbaop@gmail.com"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
